### GET all users
GET http://localhost:3000/users
Content-Type: application/json

### POST new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Teszt elek",
    "email": "test@tester.hu",
    "password": "Jelszo123"
}


### PATCH user name and email
PATCH http://localhost:3000/users/profile
Content-Type: application/json

{
    "id": 4,
    "name": "Teszter mber",
    "email": "a@a.hu"
}


### PATCH user pass
PATCh http://localhost:3000/users/password
Content-Type: application/json

{
    "id": 4,
    "currentPass": "Jelszo123",
    "newPass": "Jelszo123"
}

### post login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "a@a.hu",
    "password": "abc"
}